### ISSUE TITLE
Create threads instead of multiple new posts

### ISSUE THREAD

**Issue by silkevicious** [pla1/FediPhoto#14]
As per my proposal also in fediverse (here the link to the [THREAD](https://bikeshed.party/notice/9y37nuk7luLHSwUB7o) ), i would ask if it's possible to split the main window in 2:
- the top part will work as usual, making a new post each time it's pressed and shoot a pic.
- the bottom part will reply to the latest post created before, thus creating a thread with all the photos of a trip (or else).
Actual account and status config i don't know, it's ok placed anywhere. 🙂

This could make more 'usable' for other fedi followers see all the day/trip images just by opening the thread, instead of opening TL or profile (imho).

Things not yet defined (need discussion):
-the reply part doesn't fit Pixelfed. Should we hide it if a pixelfed account is chosen?
-(on first use) should we hide the reply part until one make a post or just 'manage' it under the hood, and make it work like the top part?

Thanks in advance! 😃

**Comment by xmgz** [comment]
thanks for opening this issue. Yes, i**t makes sense to group in a thread the pictures for a particular ride**.

I'd like to add that this feature could be implemented on the "status config" instead, with checkmark for "create thread", so create a status config on purpose.

I'm not programmer so I don't know exactly what info comes in the confirmation from server that status has been published correctly we actually receive. May be that in that server reply comes some status-ID that could be use to create a thread.

About pixelfed and threads, just make it work for pleroma/mastodon, because _threads_ are not what we usually see in pixelfed.

**Comment by pla1** [comment]
I think the Status Config is the place for this. Take a look at the threading radio buttons. Hopefully that works for everyone. Personally I will probably using the daily thread option. The only time you'll use the Start new thread button is if you want to start fresh in "Always" mode. Or if you want to start fresh in the middle of the day using "Daily" mode. Otherwise daily will work automatically. 

![PLA_20200813_010554](https://user-images.githubusercontent.com/426549/90096621-c3542980-dd01-11ea-8133-eb34805a7d55.png)

**Comment by silkevicious** [comment]
I found it a nice solution! That would be ok for me! Thank you!
And, how to disable this if a pixelfed account is selected?

**Comment by pla1** [comment]
We can't really disable it in the UI since it is defined in the status config that could be used for any type account. The best we can do is note in the app description that threading is not available for PixelFed accounts.

**Comment by silkevicious** [comment]
Thank you for adding this, you're the best! 👍
Closing now
